"""
File-based listing manager - alternative to Etsy API
Manages listings as files that can be manually uploaded to Etsy
"""
import os
import json
import shutil
from pathlib import Path
from typing import List, Dict, Optional
from datetime import datetime
from app.config import get_settings

settings = get_settings()


class FileListingManager:
    """Manage listings as files for manual Etsy upload"""
    
    def __init__(self):
        self.listings_dir = Path(settings.database_path).parent / 'listings'
        self.listings_dir.mkdir(parents=True, exist_ok=True)
        self.listings_file = self.listings_dir / 'listings.json'
        self._load_listings()
    
    def _load_listings(self):
        """Load listings from JSON file"""
        if self.listings_file.exists():
            with open(self.listings_file, 'r') as f:
                self.listings = json.load(f)
        else:
            self.listings = []
    
    def _save_listings(self):
        """Save listings to JSON file"""
        with open(self.listings_file, 'w') as f:
            json.dump(self.listings, f, indent=2)
    
    def create_listing(
        self,
        title: str,
        description: str,
        pdf_path: str,
        images: List[str],
        price: float = None,
        tags: List[str] = None
    ) -> Dict:
        """
        Create a new listing as files
        
        Args:
            title: Listing title
            description: Listing description
            pdf_path: Path to PDF file
            images: List of image file paths
            price: Listing price
            tags: List of tags
            
        Returns:
            Dictionary with listing information
        """
        # Create unique listing ID
        listing_id = f"listing_{datetime.now().strftime('%Y%m%d%H%M%S%f')}"
        
        # Create listing directory
        listing_dir = self.listings_dir / listing_id
        listing_dir.mkdir(exist_ok=True)
        
        # Copy PDF to listing directory
        pdf_name = f"{title[:50].replace(' ', '_')}.pdf"
        pdf_dest = listing_dir / pdf_name
        shutil.copy2(pdf_path, pdf_dest)
        
        # Copy images to listing directory
        image_files = []
        for i, image_path in enumerate(images[:5]):  # Max 5 images
            ext = Path(image_path).suffix
            image_name = f"image_{i+1}{ext}"
            image_dest = listing_dir / image_name
            shutil.copy2(image_path, image_dest)
            image_files.append(image_name)
        
        # Create listing metadata file
        listing_data = {
            'id': listing_id,
            'title': title,
            'description': description,
            'price': price or settings.etsy_default_price,
            'quantity': settings.etsy_default_quantity,
            'tags': tags or [],
            'pdf_file': pdf_name,
            'image_files': image_files,
            'created_at': datetime.now().isoformat(),
            'status': 'ready'  # ready for manual upload
        }
        
        # Save to listings JSON
        self.listings.append(listing_data)
        self._save_listings()
        
        # Create README file for the listing
        readme_content = f"""# {title}

## Listing Details
- **Price**: ${listing_data['price']:.2f}
- **Quantity**: {listing_data['quantity']}
- **Status**: {listing_data['status']}

## Description
{description}

## Tags
{', '.join(listing_data['tags'])}

## Files in This Directory
- {pdf_name} (Main PDF file)
{chr(10).join([f"- {img}" for img in image_files])}

## How to Upload to Etsy

1. Log into your Etsy shop
2. Click "Add a listing"
3. Fill in the listing details:
   - **Title**: {title}
   - **Description**: Use the description above
   - **Price**: ${listing_data['price']:.2f}
   - **Quantity**: {listing_data['quantity']}
   - **Tags**: {', '.join(listing_data['tags'])}
4. Upload images:
   - First image: {image_files[0] if image_files else 'N/A'} (will be main image)
   - Additional images: {', '.join(image_files[1:]) if len(image_files) > 1 else 'None'}
5. Upload digital file:
   - Select the PDF file: {pdf_name}
   - Set as "Digital download"
6. Review and publish

---
Generated by AutoLister on {datetime.now().strftime('%Y-%m-%d %H:%M')}
"""
        
        with open(listing_dir / 'README.txt', 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        return listing_data
    
    def get_listing(self, listing_id: str) -> Optional[Dict]:
        """Get a specific listing by ID"""
        for listing in self.listings:
            if listing['id'] == listing_id:
                return listing
        return None
    
    def get_all_listings(self, status: str = None) -> List[Dict]:
        """Get all listings, optionally filtered by status"""
        if status:
            return [l for l in self.listings if l.get('status') == status]
        return self.listings
    
    def update_status(self, listing_id: str, status: str) -> bool:
        """Update the status of a listing"""
        for listing in self.listings:
            if listing['id'] == listing_id:
                listing['status'] = status
                self._save_listings()
                return True
        return False
    
    def delete_listing(self, listing_id: str) -> bool:
        """Delete a listing and its files"""
        listing = self.get_listing(listing_id)
        if not listing:
            return False
        
        # Remove listing directory
        listing_dir = self.listings_dir / listing_id
        if listing_dir.exists():
            shutil.rmtree(listing_dir)
        
        # Remove from listings
        self.listings = [l for l in self.listings if l['id'] != listing_id]
        self._save_listings()
        
        return True
    
    def get_listing_files(self, listing_id: str) -> Dict:
        """Get file paths for a listing"""
        listing = self.get_listing(listing_id)
        if not listing:
            return {}
        
        listing_dir = self.listings_dir / listing_id
        if not listing_dir.exists():
            return {}
        
        return {
            'directory': str(listing_dir),
            'pdf': str(listing_dir / listing['pdf_file']),
            'images': [str(listing_dir / img) for img in listing['image_files']],
            'readme': str(listing_dir / 'README.txt')
        }
    
    def export_listings_csv(self, output_path: str = None) -> str:
        """Export all listings to CSV format"""
        if output_path is None:
            output_path = str(self.listings_dir / 'listings_export.csv')
        
        import csv
        
        with open(output_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow([
                'ID', 'Title', 'Price', 'Status', 
                'Created', 'PDF File', 'Image Count'
            ])
            
            for listing in self.listings:
                writer.writerow([
                    listing['id'],
                    listing['title'],
                    listing['price'],
                    listing['status'],
                    listing['created_at'],
                    listing['pdf_file'],
                    len(listing['image_files'])
                ])
        
        return output_path
    
    def get_statistics(self) -> Dict:
        """Get statistics about listings"""
        total = len(self.listings)
        ready = len([l for l in self.listings if l.get('status') == 'ready'])
        uploaded = len([l for l in self.listings if l.get('status') == 'uploaded'])
        
        return {
            'total': total,
            'ready': ready,
            'uploaded': uploaded,
            'pending': total - ready - uploaded
        }
